# TrainingArguments
seed: 42
max_steps: 100
report_to: none
run_name: smollm1-135m-2norm_r_4-d_kv_8-8x3090-test
save_strategy: steps
save_steps: 100
output_dir: ckpts/smollm1-135m-2norm_r_4-d_kv_8-8x3090-test
overwrite_output_dir: true
logging_strategy: steps
logging_steps: 1
resume_from_checkpoint: null
per_device_train_batch_size: 4
remove_unused_columns: False
gradient_accumulation_steps: 16
gradient_checkpointing: true
bf16: true
deepspeed: cfgs/ds_zero_1.json
dataloader_drop_last: true
# optim
optim: adamw_torch
max_grad_norm: 1.0
learning_rate: 1.0e-4
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
weight_decay: 0.0
# lr scheduler
use_constant_with_warmup_decay_scheduler: true
lr_scheduler_kwargs:
  {
    "lr_decay_starting_step": 80,
    "lr_decay_steps": 20,
    "lr_decay_style": "1-sqrt",
    "lr_warmup_steps": 10,
    "lr_warmup_style": "linear",
    "min_decay_lr": 0,
  }

# ModelArguments
model_name_or_path: HuggingFaceTB/SmolLM-135M
partial_rope_version: 2-norm # 'high'/'low'/'uniform'/'2-norm'
rope_dim_for_mla: 4
uniform_start_point: 0 # optional only for 'uniform'
qk_tensor_path: utils/smollm1_135M-2_norm_rank.pth
svd_init_method: joint # 'split'/'joint'
low_rank: 8
is_baseline: false
is_gqa2mha2mla: false

# DataArguments
is_nanoset: false
hf_dataset_name_or_path: HuggingFaceTB/smollm-corpus
hf_dataset_subset: cosmopedia-v2
sequence_length: 2048
#hf_dataset_cache_dir: /root/autodl-tmp/huggingface_cache
